spring.application.name=gs-tech-challenge
server.port=8080

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/fundscope}

jwt.secret=my-super-secret-key-that-is-at-least-256-bits-long-for-hmac-sha-signing
jwt.expiration-ms=86400000